![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [9]:
my_array = np.arange(10)
print(my_array)

print(my_array[-1:0:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [10]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [13]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [32]:
a = np.arange(1,21).reshape(4,5)
print(a)

a_inv = a[::-1]
print()
print(a_inv)
print()

for k,v in enumerate(a_inv.copy()):
    a_inv[k] = a_inv[k][::-1]
print()
print(a_inv)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [35]:
sub_mat = np.array((a_inv[-1][-1:-3:-1], a_inv[-2][-1:-3:-1]))
print(sub_mat)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [40]:
sub_mat = np.array((a_inv[-1][-1::-2], a_inv[1][-1::-2]))
print(sub_mat)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [42]:
sub_mat = np.array(((a_inv[-1]),(a_inv[-2]),(a_inv[-3])))
print(sub_mat)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [43]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [46]:
x_mask = (x=='Loro')
print(x[x_mask])

['Loro' 'Loro']


In [47]:
x_mask2 = np.where(x=='Loro', True, False)
print(x[x_mask2])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [48]:
a = np.arange(20)
print(a)
print()

b = a.reshape((2,5,2))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [49]:
a_inv

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [86]:
a = np.zeros(10)
print(a.nbytes)

a[4] = 1
print(a)

80
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [84]:
type(a[0])

numpy.float64

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [52]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [54]:
a = [1,2,0,0,4,0]
b = np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [61]:

a = np.random.randint(0,26, (10,10))
print(a)
print(np.min(a))
print(np.max(a))

[[12  5 10 18  8 24 16 21 24  3]
 [11 10 14 19 16 20 13 17 19 14]
 [ 0 11 22  6 13 10  4  2 23 16]
 [17 16 18  3  7 10 20  7 11 19]
 [21 21 18 12  7  1 22  2  7  9]
 [20  5 21  8 12  4  9  9 21 18]
 [19  9 17  6  3  4  3 25 23 23]
 [19 19 25 22 13  4 25 17 10  3]
 [13 10 23  7 17  3  4  3 22 18]
 [23 23 16 23  6 23  0  5  1  1]]
0
25


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [62]:
a = np.random.randint(10,101, (30))
print(a)
print(np.mean(a))

[29 44 40 81 19 84 70 30 91 27 76 53 90 36 17 67 59 10 38 95 20 81 71 54
 64 61 35 95 52 13]
53.4


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [152]:
a = np.ones((10,10), dtype = np.int8)
print(a)
a[1:-1,1:-1] = 0

print()
print(a)
    

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [103]:

a = np.array([0, 1, 0, 1,0,1, 0, 1])
b = a.reshape(8,1)^a
print(b)
    


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [110]:
a = np.tile([0, 1, 0, 1,0,1, 0, 1], (8,1))
for f in range(len(a)):
    if f%2:
        a[f] = a[f]^1
    else:
        pass

print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [113]:
a = np.random.randint(10, 101, (5,5))
b = (a - np.mean(a))/np.std(a)
print(a)
print(b)

[[27 13 50 87 68]
 [56 53 74 24 39]
 [34 78 40 37 61]
 [30 26 62 80 16]
 [64 85 92 40 29]]
[[-1.02196108 -1.62820917 -0.02598206  1.57624505  0.75347978]
 [ 0.23383855  0.10392824  1.01330039 -1.15187138 -0.50231985]
 [-0.71883703  1.18651413 -0.45901642 -0.58892672  0.45035573]
 [-0.89205077 -1.06526451  0.49365916  1.273121   -1.49829887]
 [ 0.58026603  1.48963818  1.79276223 -0.45901642 -0.9353542 ]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [134]:
a = np.arange(0,11)
print(a)
a_mask3 = np.where(a>3, True, False)
a_mask8 = np.where(a<8, True, False)
a_mask = a_mask3 & a_mask8
print(a[a_mask])

[ 0  1  2  3  4  5  6  7  8  9 10]
[4 5 6 7]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [167]:
import numpy.random as rnd
def disparo(tablero, coordenada):
    if tablero[coordenada[0], coordenada[1]] == 'O':
        tablero[coordenada[0], coordenada[1]] = 'X'
    elif tablero[coordenada[0], coordenada[1]] == ' ':
        tablero[coordenada[0], coordenada[1]] = '-'
    else:
        pass

def colocar_barco(tablero,tamanio = 4, orientacion = 'O'):
    my_orien = {'S':(-1,0), 'N':(1,0), 'E':(0,1), 'O':(0,-1)}
    x = rnd.randint(10)
    y = rnd.randint(10)
    x_def, y_def = x,y
    for e in range(tamanio):
        if tablero[x,y] == ' ':
            x += my_orien[orientacion][0]
            y += my_orien[orientacion][1]

            continue
        else:
            return 'No pude colocar el barco'
    
    # Si el barco se puede colocar, lo coloca
    for e in range(tamanio):
        tablero[x_def,y_def] = 'O'
        x_def += my_orien[orientacion][0]
        y_def += my_orien[orientacion][1]
    
    return 'Barco colocado!'
        
        
    

In [172]:
tablero = np.full((10,10), ' ')
barcos = [(0,1),(1,1),(1,3),(1,4),(1,5),(1,6)]
for i,j in barcos:
    tablero[i,j] = 'O'
    
#print(tablero)



print()
disparo(tablero, (0,1))
disparo(tablero, (3,1))
print(colocar_barco(tablero))
print(colocar_barco(tablero))
print(tablero)



No pude colocar el barco
No pude colocar el barco
[[' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
