![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
my_array[-1::-2]

array([9, 7, 5, 3, 1])

In [5]:
my_array[9::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
print(my_array[-2:-4:-1])

[8 7]


In [8]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [11]:
print(my_array)
print(my_array[2::-1])
print(my_array[-8:-11:-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1, 21).reshape(4,5)
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
my_matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [14]:
np.flip(my_matrix)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [16]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
my_matrix[:2, :2]

array([[1, 2],
       [6, 7]])

In [18]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [8]:
my_matrix = np.arange(1, 21).reshape((4,5))
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
my_matrix[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [20]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
my_matrix[:3:, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [22]:
my_matrix[:-1:, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [26]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
# 1.
x_loro = np.array(x == "Loro")
print(x_loro)

x[x_loro]

[ True False False  True False]


array(['Loro', 'Loro'], dtype='<U5')

In [27]:
# 2.
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [28]:
# 3.
x[np.where(x=="Loro")]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [29]:
x = np.arange(20).reshape(2,5,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [30]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [33]:
x = np.zeros(10)
print(x)

print(x.nbytes)
print(x.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
8


In [34]:
x[3] = 1
print(x)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [35]:
x = np.arange(10, 50)
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [43]:
x = np.array([1,2,0,0,4,0])
print(x)

[1 2 0 0 4 0]


In [46]:
x == 0

array([False, False,  True,  True, False,  True])

In [44]:
np.where(x == 0, 6, x)

(array([2, 3, 5], dtype=int64),)

In [50]:
bool(2)

True

In [45]:
np.where([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [42]:
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [49]:
x = np.array([[1,2],[0,0]])
print(x)
np.where(x == 0)

[[1 2]
 [0 0]]


(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [55]:
x = np.random.randint(1, 100, size=(10,10))
print(x)

print(np.min(x))
print(np.max(x))
print(x.max())

[[79 43 21 72 62 64 15 54 20 42]
 [58 29 71 44 78 32 47 78 90 88]
 [60 52 70 85 88 56 87 44 59 81]
 [36 60 15  4 18 19 74 81  6 12]
 [26 33 88 61 10 62  3 87 87 93]
 [73 60 49 52 36 30 12 45 64 39]
 [17 93 46  7 24 42 52 49 77 91]
 [49 44 68 95  1 97 44 51  5 51]
 [89 83 29 74 74 44 23 61  8 99]
 [78 18 63 27  3 87 26 63 43 29]]
1
99
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [56]:
x = np.random.random(30)
m = x.mean()
print(m)

0.47438292775104524


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [58]:
import numpy as np

x = np.ones((10,10), np.int32)
x[1:-1, 1:-1] = 0
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [66]:
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [63]:
a = np.array([0, 1, 0, 1, 0, 1, 0, 1])
print(a)
print(a.reshape(8,1))
b = a.reshape(8,1)^a
print(b)

[0 1 0 1 0 1 0 1]
[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [69]:
x = np.zeros((8,8), np.int32)
print(x)

x[1::2, 0::2] = 1
print(x)
print("salto")

y = np.zeros((8,8), np.int32)
y[0:-1:2, 1::2] = 1
print(y)
print("salto")
print(x+y)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
salto
[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]
salto
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [70]:
x = np.tile(np.array([[0,1], [1,0]]),
           (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [74]:
x = np.random.randint(1,20, (5,5))
print(x)

media = np.mean(x)
stdev = np.std(x)

x = (x - media)/stdev
print(x)

[[ 8 17 17  3 15]
 [ 9 16 19  1 14]
 [10  1  6 13 17]
 [14  3 19  3  3]
 [ 6  6 11 13 11]]
[[-0.38135638  1.17873792  1.17873792 -1.24807544  0.83205029]
 [-0.20801257  1.00539411  1.52542554 -1.59476306  0.65870648]
 [-0.03466876 -1.59476306 -0.72804401  0.48536267  1.17873792]
 [ 0.65870648 -1.24807544  1.52542554 -1.24807544 -1.24807544]
 [-0.72804401 -0.72804401  0.13867505  0.48536267  0.13867505]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [78]:
(x > 3) & (x < 8)

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False])

In [77]:
x = np.arange(11)
print(x)

np.where((x > 3) & (x < 8), -1, x)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

In [79]:
x = np.arange(11)
print(x)

x[(x > 3) & (x < 8)] = -1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [82]:
x = np.arange(11)
print(x)
x = x*(-1)
x

[ 0  1  2  3  4  5  6  7  8  9 10]


array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [84]:
x = np.arange(11)
print(x)
x[(x > 3) & (x < 8)] = x[(x > 3) & (x < 8)] * -1
x[(x > 3) & (x < 8)] *= -1 # Equivalente
x

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [ ]:
contador = 0

contador+=1
contador=contador+1

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.